// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-TF7hIODCvAwpFYHwjx7J4Qie_mihHXI',
    appId: '1:509786778688:web:7704cd85806b36581203a5',
    messagingSenderId: '509786778688',
    projectId: 'harvesthub-ea21c',
    authDomain: 'harvesthub-ea21c.firebaseapp.com',
    storageBucket: 'harvesthub-ea21c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDeYOrCpJIhQD3SM0OmReEg9l_CAda7w',
    appId: '1:509786778688:android:6242ec2146ca398b1203a5',
    messagingSenderId: '509786778688',
    projectId: 'harvesthub-ea21c',
    storageBucket: 'harvesthub-ea21c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2moRafUGus9TxmTsToV7Q-Vc8XF2Zrrk',
    appId: '1:509786778688:ios:8a49f35187c1f8911203a5',
    messagingSenderId: '509786778688',
    projectId: 'harvesthub-ea21c',
    storageBucket: 'harvesthub-ea21c.firebasestorage.app',
    iosBundleId: 'com.example.harvestHub',
  );
}
